INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (1, 400.00, null, '18%', 'Smietana', 5.00, 'GRAM', 1);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (2, 1.00, null, '3.2% butelka', 'Mleko Laciate', 5.00, 'LITERS', 2);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (3, 1.00, null, '2.0% butelka', 'Mleko Laciate', 5.00, 'LITERS', 2);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (4, 1.00, null, '3.2% karton', 'Mleko Laciate', 5.00, 'LITERS', 2);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (5, 1.00, null, '2.0% karton', 'Mleko Laciate', 5.00, 'LITERS', 2);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (6, 1.00, null, '0.5% karton', 'Mleko Laciate', 5.00, 'LITERS', 2);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (7, 0.50, null, '3.2% karton', 'Mleko Laciate', 5.00, 'LITERS', 2);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (8, 0.50, null, '2.0% karton', 'Mleko Laciate', 5.00, 'LITERS', 2);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (9, 0.50, null, '0.5% karton', 'Mleko Laciate', 5.00, 'LITERS', 2);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (10, 400.00, null, 'kubek', 'Kefir', 5.00, 'GRAM', 3);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (11, 400.00, null, 'butelka', 'Kefir', 5.00, 'GRAM', 3);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (12, 150.00, null, 'Jogobella standard', 'Jogurt', 5.00, 'GRAM', 4);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (13, 150.00, null, 'Jogobella specjal', 'Jogurt', 5.00, 'GRAM', 4);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (14, 400.00, null, 'Jogobella classic', 'Jogurt', 5.00, 'GRAM', 4);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (15, 100.00, null, 'Osełka górska', 'Masło', 5.00, 'GRAM', 5);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (16, 300.00, null, 'Osełka górska', 'Masło', 5.00, 'GRAM', 5);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (17, 200.00, null, 'Mix pasłęcki', 'Masło', 5.00, 'GRAM', 6);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (18, 450.00, null, 'Słonecznikowy', 'Chleb', 5.00, 'GRAM', 7);
INSERT INTO financemanager.products (id_product, amount, category, description, name, tax, unit, producer_id) VALUES (19, 450.00, null, 'Żytni', 'Chleb', 5.00, 'GRAM', 7);